<?php

namespace App\Repository;

/**
 * ApiKey
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiKey extends \Doctrine\ORM\EntityRepository
{
}
