<?php

namespace App\Repository;

/**
 * Location
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Location extends \Doctrine\ORM\EntityRepository
{
}
