<?php

namespace App\Repository;

/**
 * Postcode
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Postcode extends \Doctrine\ORM\EntityRepository
{
}
